#hbase:
#  image: 103.31.151.220:5000/harisekhon/hbase:1.2
#  hostname: hbase
#  container_name: hbase
#  volumes:
#  - ./conf/hbase/:/hbase/conf
#  - /data/docker-data/hbase:/tmp/hbase-root
#  net: "hadoop"
#  ports:
#  - "2181:2181"
#  - "8090:8080"
#  - "8085:8085"
#  - "9090:9090"
#  - "9095:9095"
#  - "16000:16000"
#  - "16010:16010"
#  - "16201:16201"
#  - "16301:16301"
 # restart: always

master:
  image: 103.31.151.220:5000/mesosphere/spark:1.0.6-2.0.2-hadoop-2.6
#  links:
#  - hbase:hbase
  volumes:
    - ../../target/scala-2.11/import-export-assembly-1.0.jar:/tmp/
  hostname: master
  container_name: master
  net: "hadoop"
  ports:
  - "4040:4040"
  - "8042:8042"
  - "7077:7077"
  - "8088:8088"
  - "8080:8080"
 # restart: always
  command: bash /opt/spark/dist/sbin/start-master.sh && ping localhost > /dev/null

worker:
  image: 103.31.151.220:5000/mesosphere/spark:1.0.6-2.0.2-hadoop-2.6
  links:
  - master:master
#  - hbase:hbase
  container_name: worker
  net: "hadoop"
  expose:
  - "8081"
 # restart: always
  command: bash /opt/spark/dist/sbin/start-slave.sh spark://master:7077 && ping localhost >/dev/null
